### ISSUE TITLE
Unreadable text in dark theme

### ISSUE THREAD

**Issue by sorawee** [racket/macro-debugger#35]
When running the macro stepper via `raco macro-stepper`, the text area has white background, causing some text to be unreadable.

<img width="571" alt="Screen Shot 2021-03-11 at 12 39 47 AM" src="https://user-images.githubusercontent.com/9099577/110672534-4e4ac300-8202-11eb-951e-4b49d14fa6be.png">

**Comment by rfindler** [comment]
Maybe the code needs to use `text:foreground-color-mixin` and `canvas:color-mixin`?

**Comment by rmculpepper** [comment]
The editor does use `text:foreground-color-mixin`, and the canvas is already a `canvas:color%`.

I haven't managed to reproduce the problem (on Ubuntu or on Mac OS). Can you check whether it still exists? If so, what platform, and what combination of configurations (OS and DrRacket) makes it happen?

**Comment by sorawee** [comment]
It still exists. Mac OS and DrRacket 8.0.0.13--2021-04-05(e8f857cc/d) [cs].

**Comment by sorawee** [comment]
Aha! I think the part that we missed earlier is that it's related to theme. Tol's White on Black (installed by default) and Spacemacs Dark (user installed) seems to trigger the issue, but White on Black (installed by default) does not.

**Comment by rmculpepper** [comment]
Thanks, that helped! I've pushed a fix.
