### ISSUE TITLE
Inconsistent doc for `check-requires`

### ISSUE THREAD

**Issue by Metaxal** [racket/macro-debugger#37]
The docs for [check-requires](https://docs.racket-lang.org/macro-debugger/index.html?q=check-requires#%28def._%28%28lib._macro-debugger%2Fanalysis%2Fcheck-requires..rkt%29._check-requires%29%29) say that 
> by default, only DROP recommendations are printed.

but this is inconsistent with the default values in the `defproc`:
```racket
show-keep? : boolean? = #t
show-bypass? : boolean? = #t
show-drop? : boolean? = #t
show-uses? : boolean? = #f
```

**Comment by rmculpepper** [comment]
Thanks for the bug report(s)!
