### ISSUE TITLE
more derivation parser errors

### ISSUE THREAD

**Issue by florence** [racket/macro-debugger#8]
Internal error:
derivation-parser: error on token #529: <syntax-error, #(struct:exn:fail:syntax:unbound "blaahh: unbound identifier in module (in phase 1, transformer environment)" #<continuation-mark-set> (#<syntax:/Users/florence/tmp/blah.rkt:5:30 blaahh>))>

```
#lang racket
(define-syntax (foo) bar)
```

**Comment by rmculpepper** [comment]
This works in the current pre-release.
